version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres://postgres:password@db:5432/portfolio_development
      RAILS_ENV: development
    volumes:
      - .:/portfolio
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: